<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="4" time="0.119" timestamp="2023-10-24T18:04:42.387285" hostname="Yugesh"><testcase classname="Regression.sample.TestAddition" name="test_add_mixed_numbers" time="0.001" /><testcase classname="Regression.sample.TestAddition" name="test_add_negative_numbers" time="0.001" /><testcase classname="Regression.sample.TestAddition" name="test_add_positive_numbers" time="0.001" /><testcase classname="Regression.sample.TestAddition" name="test_new" time="0.001"><failure message="AssertionError: 6 != -1">self = &lt;sample.TestAddition testMethod=test_new&gt;

    def test_new(self):
&gt;       self.assertEqual(add(9, -3), -1)  # Assert that add(2, -3) is equal to -1
E       AssertionError: 6 != -1

Regression\sample.py:22: AssertionError</failure></testcase></testsuite></testsuites>